name: Validate retrieve-image-tags config
on:
  pull_request:
    paths:
      - 'retrieve-image-tags/**'

permissions:
  contents: read

jobs:
  validate-retrieve-image-tags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: Validate JSON
      run: jq type retrieve-image-tags/config.json
    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Pip
      working-directory: ./retrieve-image-tags
      run: pip install -r requirements.txt
    - id: gimme-versions
      working-directory: ./retrieve-image-tags
      run: |
        python retrieve-image-tags.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
